extends Node
#Health
var healthP1 = 0
var healthP2 = 3
#Who owns the turn
var ownsTurn = 0
#Amount of cards on players hand
var cardAmountP1 = 0
var cardAmountP2 = 0
#Which hands are in players hand
var cardHandP1 = {}
var cardHandP2 = {}
#Are we in the state of a saveround? (The one who started has 5 cards)
var saveRound = false
#Has someone won?
var endgame = false
#Who owned the first round
var firstRound = 0
#Total sum of cards in hand
var cardSumP1 = 0
var cardSumP2 = 0
# Who wins
var winP1 = false
var winP2 = false
#Turn number
var turnNumber = 0
#How many cards are in the center
var centerCards = 0
var centerHand = []
#How many cards to give (calculation purposes)
var cardsGive = 0
#Array of cards generated by getRandomCards
var cardsGenerated = []
#Saved turn number for getRandomCards

func getRandomCards():
	#Calculate how many cards have to be generated
	cardsGive = (centerCards - 5) * -1
	#Get keys and shuffle
	var keys = Globals.cardDict.keys()
	keys.shuffle()
	#Tricky one, grabs the amount of keys, checks that there aren't more keys asked than in dictionary
	var cardsGenerated = keys.slice(0, min(cardsGive, keys.size()))
	#Erases cards from dictionary
	for card in cardsGenerated:
		Globals.cardDict.erase(card)
	centerHand.append_array(cardsGenerated)
	print(centerHand)

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	getRandomCards()
	getRandomCards()
	


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	if turnNumber == 0:
		ownsTurn = randi_range(1,2)
	else:
		if ownsTurn == 1:
			ownsTurn = 2
		else:
			ownsTurn = 1
	#Checking if someone is dead
	if healthP2 == 0 or healthP1 == 0:
		endgame = true
		print("Endgame.")
		return
	else:
		#Checking if a saveround is happening
		if cardAmountP2 or cardAmountP1 == 5:
			if firstRound == 2 and cardAmountP2 == 5 or cardAmountP1 == 5 and firstRound == 1:
				saveRound = true
			else:
				#Checking who has more cards
				if cardSumP1 > cardAmountP2:
					winP1 = true
					endgame = true
				else:
					winP2 = true
					endgame = true
		else:
			pass
			#getRandomCards()
